name: 'Prettier, please!'
description: 'Formats your code and documentation with Prettier, if you ask nicely.'
author: 'Reid Draper'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
